[build]
  command = "CI = npm run build"
  commandOrigin: config
  environment:
    - CI
    - authkey
    - authkey
    - secret

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/"
