[build]
  command = "npm run build"
  publish = "public"

[context.production]
  environment = { CI = "npm run build" }

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/"
